"""
Writer Agent - Generates comprehensive research reports.
"""

import json
import logging
from typing import Any

import httpx
from jinja2 import Template

logger = logging.getLogger(__name__)

REPORT_TEMPLATE = """# {{ title }}

**Research Report Generated by DeepResearch Agent**
*Date: {{ date }} | Confidence: {{ confidence }}%*

---

## Executive Summary

{{ summary }}

## Key Findings

{% for finding in findings %}
{{ loop.index }}. {{ finding }}
{% endfor %}

## Detailed Analysis

{{ analysis }}

## Data Points & Statistics

{% for point in data_points %}
- {{ point }}
{% endfor %}

## Expert Opinions

{% for opinion in expert_opinions %}
> {{ opinion }}
{% endfor %}

## Patterns Identified

{% for pattern in patterns %}
- {{ pattern }}
{% endfor %}

## Contradictions & Limitations

{% if contradictions %}
{% for contradiction in contradictions %}
⚠️ {{ contradiction }}
{% endfor %}
{% else %}
No significant contradictions found.
{% endif %}

## Information Gaps

{% for gap in gaps %}
- {{ gap }}
{% endfor %}

## Citations

{% for citation in citations %}
{{ loop.index }}. [{{ citation.title }}]({{ citation.url }})
{% endfor %}

## Methodology

This report was generated using autonomous multi-source research:
- **Sources consulted:** {{ source_count }}
- **Research depth:** {{ depth }}
- **Agents used:** Planner → Researcher → Analyst → Writer → Critic

---

*Report generated by DeepResearch Agent - Open Source Autonomous Research*
"""


class WriterAgent:
    """
    Autonomous writing agent that generates comprehensive reports.
    
    Features:
    - Structured report generation
    - Citation management
    - Multiple output formats (Markdown, HTML)
    - Report revision based on critic feedback
    """
    
    def __init__(self, config: dict[str, Any]):
        self.config = config
        self.llm_endpoint = config.get("llm_endpoint", "https://api.mimo.xiaomi.com/v1/chat/completions")
        self.llm_key = config.get("llm_key", "")
        self.model = config.get("model", "mimo-7b")
    
    async def generate_report(
        self,
        topic: str,
        plan: dict[str, Any],
        analysis: dict[str, Any],
        sources: list[dict[str, Any]]
    ) -> str:
        """
        Generate a comprehensive research report.
        
        Args:
            topic: The research topic
            plan: The research plan
            analysis: The analysis results
            sources: The sources found
            
        Returns:
            Generated report in Markdown format
        """
        logger.info(f"Generating report for: {topic}")
        
        # Generate report content using LLM
        prompt = f"""You are a research report writer. Write a comprehensive report about:

TOPIC: {topic}

ANALYSIS:
{json.dumps(analysis, indent=2)}

SOURCES FOUND: {len(sources)}

Write a detailed, well-structured report with:
1. Executive summary (2-3 paragraphs)
2. Detailed analysis sections
3. Data points and statistics
4. Expert opinions
5. Patterns and trends
6. Limitations and gaps

Use Markdown formatting. Be thorough and professional.
Include specific data points from the analysis."""

        try:
            report_content = await self._call_llm(prompt)
            
            # Build final report with template
            from datetime import datetime
            
            report = REPORT_TEMPLATE.render(
                title=f"Research Report: {topic}",
                date=datetime.now().strftime("%Y-%m-%d %H:%M"),
                confidence=f"{analysis.get('confidence_score', 0) * 100:.0f}",
                summary=report_content[:500] + "..." if len(report_content) > 500 else report_content,
                findings=analysis.get("key_findings", []),
                analysis=report_content,
                data_points=analysis.get("data_points", []),
                expert_opinions=analysis.get("expert_opinions", []),
                patterns=analysis.get("patterns", []),
                contradictions=analysis.get("contradictions", []),
                gaps=analysis.get("gaps", []),
                citations=analysis.get("citations", []),
                source_count=len(sources),
                depth=plan.get("research_depth", "medium")
            )
            
            logger.info(f"Report generated: {len(report)} characters")
            return report
            
        except Exception as e:
            logger.error(f"Report generation failed: {e}")
            return self._fallback_report(topic, analysis, sources)
    
    async def revise_report(
        self,
        original_report: str,
        critique: dict[str, Any],
        topic: str
    ) -> str:
        """
        Revise report based on critic feedback.
        
        Args:
            original_report: The original report
            critique: Critic's feedback
            topic: The research topic
            
        Returns:
            Revised report
        """
        logger.info("Revising report based on critic feedback")
        
        prompt = f"""You are a research report editor. Revise this report based on feedback:

ORIGINAL REPORT:
{original_report}

CRITIC FEEDBACK:
{json.dumps(critique, indent=2)}

Improve the report by:
1. Addressing all issues mentioned in feedback
2. Enhancing weak sections
3. Adding more detail where needed
4. Improving clarity and flow

Return the complete revised report in Markdown format."""

        try:
            revised = await self._call_llm(prompt)
            logger.info(f"Report revised: {len(revised)} characters")
            return revised
        except Exception as e:
            logger.error(f"Revision failed: {e}")
            return original_report
    
    async def _call_llm(self, prompt: str) -> str:
        """Call the LLM endpoint."""
        async with httpx.AsyncClient() as client:
            response = await client.post(
                self.llm_endpoint,
                headers={
                    "Authorization": f"Bearer {self.llm_key}",
                    "Content-Type": "application/json"
                },
                json={
                    "model": self.model,
                    "messages": [
                        {"role": "system", "content": "You are a professional report writer. Write comprehensive, well-structured reports."},
                        {"role": "user", "content": prompt}
                    ],
                    "temperature": 0.7,
                    "max_tokens": 3000
                },
                timeout=60.0
            )
            
            if response.status_code == 200:
                return response.json()["choices"][0]["message"]["content"]
            else:
                raise Exception(f"LLM API error: {response.status_code}")
    
    def _fallback_report(self, topic: str, analysis: dict[str, Any], sources: list[dict[str, Any]]) -> str:
        """Create a basic fallback report."""
        from datetime import datetime
        
        findings = analysis.get("key_findings", ["No findings available"])
        citations = analysis.get("citations", [])
        
        return f"""# Research Report: {topic}

**Generated:** {datetime.now().strftime("%Y-%m-%d %H:%M")}

## Summary

This report presents findings from autonomous research on: {topic}

## Key Findings

{chr(10).join(f'- {f}' for f in findings)}

## Sources

{chr(10).join(f'{i+1}. [{c.get("title", "Source")}]({c.get("url", "#")})' for i, c in enumerate(citations[:5]))}

---
*Generated by DeepResearch Agent*
"""
